### ISSUE TITLE
Compatibility with shiro annotations

### ISSUE THREAD

**Issue by a-langer** [gk-brown/HTTP-RPC#89]
Do not work access control annotations from the framework "Shiro" https://shiro.apache.org/java-authorization-guide.html (used shiro and guice).
Example:
```java
    @RequiresRoles("admin") // This is shiro annotations 
    @RequestMethod("GET")
    @ResourcePath("/example")
    public Map<String, Object> getExample() {
        Map<String, Object> jsonMap = new LinkedHashMap<>();
        jsonMap.put("Hello", "World");
        return jsonMap;
    }
```
Response: 
```text
405 HTTP method GET is not supported by this URL 
```
Response without annotation @RequiresRoles("admin") : 
```javascript
{
  "Hello": "World"
}
```

**Comment by a-langer** [comment]
In the default servlet, annotations work fine.
Example:
```java
@Singleton
@WebServlet(name="HelloServlet")
public class HelloServlet extends HttpServlet {

    @RequiresRoles("admin")
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html");
        response.setStatus(HttpServletResponse.SC_OK);
        response.getWriter().println("<h1> HelloServlet !</h1>");
    }
}
```
Response:
```text
<h1> HelloServlet !</h1>
```

**Comment by gk-brown** [comment]
Thanks for the suggestion. This is a reasonable request, but it would require a dependency on Shiro. One of the project's goals is to depend only on the JDK and servlet API.

Instead, I have prototyped an enhancement that will allow a service to authorize a request by overriding a new method in `WebService`:

```java
protected boolean isAuthorized(HttpServletRequest request, Method method) {
    ...
}
```

This method returns `true` by default. However, you should be able to override it in your service to check for the presence and value of the `RequiresRoles` annotation. I haven't used Shiro myself, but I would imagine that it provides an API you can use to programmatically (rather than declaratively) validate access.

This update is currently available on the "development" branch.

**Comment by a-langer** [comment]
Yes, in Shiro programmatically access check is performed as follows:
```java
Subject currentUser = SecurityUtils.getSubject();
if (currentUser.hasRole("admin") == false) {
    response.sendError(HttpServletResponse.SC_FORBIDDEN);
    return;
}
```
If I understand everything correctly, then in your implementation it will look like this:
```java
@Override
protected boolean isAuthorized(HttpServletRequest request, Method method) {
    Subject currentUser = SecurityUtils.getSubject();
    if (currentUser.hasRole("admin") == false) {
        return false;
    }
    return true;
}
```
In this case, we can also use Shiro (or other) annotations:
```java
@Override
protected boolean isAuthorized(HttpServletRequest request, Method method) {
    // Shiro annotations @RequiresRoles("admin")
    RequiresRoles requiresRoles = method.getAnnotation(RequiresRoles.class);
    if (requiresRoles != null) {
        String role = requiresRoles.value(); 
        Subject currentUser = SecurityUtils.getSubject();
        if (currentUser.hasRole(role) == false) {
            getResponse().sendError(HttpServletResponse.SC_FORBIDDEN);
            return false;
        }
    }
    return true;
}
```
Looks great :+1:

**Comment by a-langer** [comment]
Sorry, I accidentally closed the ticket. Tell me, please, when will the new version be released in Maven repository?

**Comment by gk-brown** [comment]
I'll try to publish it sometime later today.

**Comment by a-langer** [comment]
I noticed that the method "isAuthorized" is executed before saving the request and response. [see rows](https://github.com/gk-brown/HTTP-RPC/blob/development/httprpc/src/main/java/org/httprpc/WebService.java#L300-L316) . This means that the method "getResponse()" returns null. HttpServletResponse may be needed, for example, to present a custom error message:
```java
@Override
protected boolean isAuthorized(HttpServletRequest request, Method method) throws IOException {
    Subject currentUser = SecurityUtils.getSubject();
    if (currentUser.hasRole("admin") == false) {
       String customError = "Subject does not have role [admin]";
       getResponse().sendError(HttpServletResponse.SC_FORBIDDEN, customError);
        return false;
    }
    return true;
}
```
but in this case we will have to catch "IOException". I propose to make this method more universal, for example:
```java
protected boolean isAuthorized(HttpServletRequest request, HttpServletResponse response, Method method) 
    throws IOException, ServletException {
    return true;
}
```

**Comment by gk-brown** [comment]
That's intentional. The thread-local variables are only intended for use by the service method, so they are only set once we know the method will be invoked.

Additionally, `isAuthorized()` is intended to be an idempotent operation - it should not modify the state of the response. `WebService` will automatically return an HTTP 403 if `isAuthorized()` returns `false`.

**Comment by a-langer** [comment]
Ok, I understand you. Thank.

**Comment by gk-brown** [comment]
This is done.
