### ISSUE TITLE
Parameters: colons handling problems in various situations

### ISSUE THREAD

**Issue by porchy13** [gk-brown/HTTP-RPC#92]
Hi, 

Considering the query below, when colons are used in other way than defining parameters, the Parameters class handle them as empty parameters.

```sql
-- Warning: the colon is in a comment
select
  foo.id,
  foo.name || ':' || foo.value
from foo
where foo.name like :name;
```

When parsing a query, Parameters should ignore those empty parameters.

Regards,

**Comment by gk-brown** [comment]
Thanks for catching this. Simplest solution might be to simply ignore empty parameters in general (rather than trying to identify colons within comments).

**Comment by gk-brown** [comment]
Actually, I think making the parser comment aware might be preferable. Otherwise, if you omitted the space following the colon, the parser would attempt to treat it as a parameter.

**Comment by gk-brown** [comment]
On the other hand, does it really matter if a parameter is encountered within a comment? It would be replaced with a "?", and the associated value would most likely be `null`. Even if the value is not `null`, the parameter shouldn't have any effect:

```sql
-- Warning: the colon is in a comment
```

becomes:

```sql
-- Warning? the colon is in a comment
```

which translates to:

```sql
-- Warning<null> the colon is in a comment
```

which should have no effect, since comments are ignored when executing the query.

Are you running into a specific issue with your example above?

**Comment by porchy13** [comment]
I think your solution is ok. I load queries from sql files and cannot have the control of what's inside. Comments are for human and the parser should not be aware of them.

But if the parser will be aware of comments, it should also handle multiline comments (/* ... */). Don't forget them ;-)

**Comment by gk-brown** [comment]
I did some testing and found that your example generates an exception (at least, using MySQL - maybe other drivers are different). 

The `Parameters` class translated both colons to parameters, but `PreparedStatement` ignored the first parameter (presumably because it is in a comment). As a result, `PreparedStatement` expected a single parameter (at index 0), but `Parameters` tried to set two values (at indexes 0 and 1). This is what generated the exception.

So, to actually fix the problem, `Parameters` may need to become comment-aware. And yes, that should include both single-line and multi-line comments.  :-)

Would appreciate a pull request if you are willing to attempt a fix!

**Comment by porchy13** [comment]
Try to remove the second column in the select clause. The colon in string concatenation is also causing the same issue that the one in the comment.

**Comment by gk-brown** [comment]
The parser should ignore the colon that is in the string (since parameters shouldn't be embedded in strings). Is that not happening?

**Comment by gk-brown** [comment]
This is fixed. `Parameters` is now comment-aware. Please let me know if you run into any additional issues.
